const quizData = [
    {
      question: "Question 1",
      img: "Q1.jpg",
      answers: {
        a: "PLAYFUL",
        b: "COMFORTING",
        c: "IRRITATED",
        d: "BORED"
      },
      correctAnswer: "a"
    },
     {
      question: "Question 2",
      img: "Q2.jpg",
      answers: {
        a: "TERRIFIED",
        b: "UPSET",
        c: "ARROGANT",
        d: "ANNOYED"
      },
      correctAnswer: "b"
    },
    {
      question: "Question 3",
      img: "Q3.jpg",
      answers: {
        a: "JOKING",
        b: "FLUSTERED",
        c: "DESIRE",
        d: "CONVINCED"
      },
      correctAnswer: "c"
    },
    {
      question: "Question 4",
      img: "Q4.jpg",
      answers: {
        a: "JOKING",
        b: "INSISTING",
        c: "AMUSED",
        d: "RELAXED"
      },
      correctAnswer: "b"
    },
    {
      question: "Question 5",
      img: "Q5.jpg",
      answers: {
        a: "IRRITATED",
        b: "SARCASTIC",
        c: "WORRIED",
        d: "FRIENDLY"
      },
      correctAnswer: "c"
    },
    {
      question: "Question 6",
      img: "Q6.jpg",
      answers: {
        a: "AGHAST",
        b: "FANTASIZING",
        c: "IMPATIENT",
        d: "ALARMED"
      },
      correctAnswer: "b"
    },
    {
      question: "Question 7",
      img: "Q7.jpg",
      answers: {
        a: "APOLOGETIC",
        b: "FRIENDLY",
        c: "UNEASY",
        d: "DISPIRITED"
      },
      correctAnswer: "c"
    },
    {
      question: "Question 8",
      img: "Q8.jpg",
      answers: {
        a: "DESPONDENT",
        b: "RELIEVED",
        c: "SHY",
        d: "EXCITED"
      },
      correctAnswer: "a"
    },
    {
      question: "Question 9",
      img: "Q9.jpg",
      answers: {
        a: "ANNOYED",
        b: "HOSTILE",
        c: "HORRIED",
        d: "PREOCCUPIED"
      },
      correctAnswer: "d"
    },
    {
      question: "Question 10",
      img: "Q10.jpg",
      answers: {
        a: "CAUTIOUS",
        b: "INSISTING",
        c: "BORED",
        d: "AGHAST"
      },
      correctAnswer: "a"
    },
    {
      question: "Question 11",
      img: "Q11.jpg",
      answers: {
        a: "TERRIFIED",
        b: "AMUSED",
        c: "REGRETFUL",
        d: "FLIRTATIOUS"
      },
      correctAnswer: "c"
    },
    {
      question: "Question 12",
      img: "Q12.jpg",
      answers: {
        a: "INDIFFERENT",
        b: "EMBARRASSED",
        c: "SKEPTICA",
        d: "DISPIRITED"
      },
      correctAnswer: "c"
    },
    {
      question: "Question 13",
      img: "Q13.jpg",
      answers: {
        a: "DECISIVE",
        b: "ANTICIPATING",
        c: "THREATENING",
        d: "SHY"
      },
      correctAnswer: "b"
    },
    {
      question: "Question 14",
      img: "Q14.jpg",
      answers: {
        a: "IRRITATED",
        b: "DISAPPOINTED",
        c: "DEPRESSED",
        d: "ACCUSING"
      },
      correctAnswer: "d"
    },
    {
      question: "Question 15",
      img: "Q15.jpg",
      answers: {
        a: "CONTEMPLATIVE",
        b: "FLUSTERED",
        c: "ENCOURAGING",
        d: "AMUSED"
      },
      correctAnswer: "a"
    },
    {
      question: "Question 16",
      img: "Q16.jpg",
      answers: {
        a: "IRRITATED",
        b: "THOUGHTFUL",
        c: "ENCOURAGING",
        d: "SYMPATHETIC"
      },
      correctAnswer: "b"
    },
    {
      question: "Question 17",
      img: "Q17.jpg",
      answers: {
         a: "DOUBTFUL",
         b: "AFFECTIONATE",
         c: "PLAYFUL",
         d: "AGHAST",
      },
      correctAnswer: "a"
    },
    {
      question: "Question 18",
      img: "Q18.jpg",
      answers: {
        a: "DECISIVE",
        b: "AMUSED",
        c: "AGHAST",
        d: "BORED",
      },
      correctAnswer: "a"
    },
    {
      question: "Question 19",
      img: "Q19.jpg",
      answers: {
        a: "arrogant",
        b: "grateful",
        c: "sarcastic",
        d: "tentative",
      },
      correctAnswer: "d"
    },
    {
      question: "Question 20",
      img: "Q20.jpg",
      answers: {
        a: "dominant",
        b: "friendly",
        c: "guilty",
        d: "horrified",
      },
      correctAnswer: "b"
    },
    {
      question: "Question 21",
      img: "Q21.jpg",
      answers: {
        a: "embarrassed",
        b: "fantasizing",
        c: "confused",
        d: "panicked",
      },
      correctAnswer: "b"
    },
    {
      question: "Question 22",
      img: "Q22.jpg",
      answers: {
        a: "preoccupied",
        b: "grateful",
        c: "insisting",
        d: "imploring",
      },
      correctAnswer: "a"
    },
    {
      question: "Question 23",
      img: "Q23.jpg",
      answers: {
        a: "contented",
        b: "apologetic",
        c: "defiant",
        d: "curious",
      },
      correctAnswer: "c"
    },
    {
      question: "Question 24",
      img: "Q24.jpg",
      answers: {
        a: "pensive",
        b: "irritated",
        c: "excited",
        d: "hostile",
      },
      correctAnswer: "a"
    },
    {
      question: "Question 25",
      img: "Q25.jpg",
      answers: {
        a: "panicked",
        b: "incredulous",
        c: "despondent",
        d: "interested",
      },
      correctAnswer: "d"
    },
    {
      question: "Question 26",
      img: "Q26.jpg",
      answers: {
        a: "alarmed",
        b: "shy",
        c: "hostile",
        d: "anxious",
      },
      correctAnswer: "c"
    },
    {
      question: "Question 27",
      img: "Q27.jpg",
      answers: {
        a: "joking",
        b: "cautious",
        c: "arrogant",
        d: "reassuring",
      },
      correctAnswer: "b"
    },
    {
      question: "Question 28",
      img: "Q28.jpg",
      answers: {
        a: "interested",
        b: "joking",
        c: "affectionate",
        d: "contented",
      },
      correctAnswer: "a"
    },
    {
      question: "Question 29",
      img: "Q29.jpg",
      answers: {
        a: "impatient",
        b: "aghast",
        c: "irritated",
        d: "reflective",
      },
      correctAnswer: "d"
    },
    {
      question: "Question 30",
      img: "Q30.jpg",
      answers: {
        a: "grateful",
        b: "flirtatious",
        c: "hostile",
        d: "disappointed",
      },
      correctAnswer: "b"
    },
    {
      question: "Question 31",
      img: "Q31.jpg",
      answers: {
        a: "ashamed",
        b: "confident",
        c: "joking",
        d: "dispirited",
      },
      correctAnswer: "b"
    },
    {
      question: "Question 32",
      img: "Q32.jpg",
      answers: {
        a: "serious",
        b: "ashamed",
        c: "bewildered",
        d: "alarmed",
      },
      correctAnswer: "a"
    },
    {
      question: "Question 33",
      img: "Q33.jpg",
      answers: {
        a: "embarrassed",
        b: "guilty",
        c: "fantasizing",
        d: "concerned",
      },
      correctAnswer: "d"
    },
    {
      question: "Question 34",
      img: "Q34.jpg",
      answers: {
        a: "aghast",
        b: "baffled",
        c: "distrustful",
        d: "terrified",
      },
      correctAnswer: "c"
    },
    {
      question: "Question 35",
      img: "Q35.jpg",
      answers: {
        a: "PUZZLED",
        b: "NERVOUS",
        c: "INSISTING",
        d: "CONTEMPLATIVE",
      },
      correctAnswer: "b"
    },
    {
      question: "Question 36",
      img: "Q36.jpg",
      answers: {
        a: "ASHAMED",
        b: "NERVOUS",
        c: "SUSPICIOUS",
        d: "INDECISIVE",
      },
      correctAnswer: "c"
    },
  ];
  
  function showQuiz() {
    const quizContainer = document.getElementById('quiz');
    let output = [];
  
    quizData.forEach((currentQuestion, questionNumber) => {
      const answers = [];
      for (letter in currentQuestion.answers) {
        answers.push(`
          <label>
            <input type="radio" name="question${questionNumber}" value="${letter}">
            ${letter} : ${currentQuestion.answers[letter]}
          </label>
        `);
      }
  
      output.push(`
    <div class="question">
      <h3>${currentQuestion.question}</h3>
      <img src="${currentQuestion.img}" alt="${currentQuestion.question}" class="quiz-image">
    </div>
    <div class="choices">
      ${answers.join('')}
    </div>
       `);
    });
  
    quizContainer.innerHTML = output.join('');
  }
  
  function showResults() {
    const answerContainers = document.getElementById('quiz').querySelectorAll('.choices');
    let numCorrect = 0;
  
    quizData.forEach((currentQuestion, questionNumber) => {
      const answerContainer = answerContainers[questionNumber];
      const selector = `input[name=question${questionNumber}]:checked`;
      const userAnswer = (answerContainer.querySelector(selector) || {}).value;
  
      if (userAnswer === currentQuestion.correctAnswer) {
        numCorrect++;
      }
    });
  
    document.getElementById('results').innerHTML = `You got ${numCorrect} out of ${quizData.length} correct!`;
  }
  
  showQuiz();
  
  document.getElementById('submit').addEventListener('click', showResults);